# To apply: kubectl apply -f NGNIX.yaml
# To check the service: kubectl get svc nginx-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.4 # Use the ARM-compatible Nginx image
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-volume
          mountPath: /usr/share/nginx/html # Mount the website folder to NGINX default HTML folder
      volumes:
      - name: website-volume
        hostPath:
          path: /mnt/media/apache/templates # Specify the path to your website folder on the host machine
          type: DirectoryOrCreate # Use this type to create the directory if it doesn't exist
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
