apiVersion: apps/v1
kind: Deployment
metadata:
  name: pairdrop-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pairdrop
  template:
    metadata:
      labels:
        app: pairdrop
    spec:
      containers:
        - name: pairdrop
          image: linuxserver/pairdrop
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pairdrop-data
              mountPath: /mnt/media/pairdrop
      volumes:
        - name: pairdrop-data
          hostPath:
            path: /mnt/media/pairdrop

---
apiVersion: v1
kind: Service
metadata:
  name: pairdrop-service
spec:
  selector:
    app: pairdrop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 32524
  type: LoadBalancer
