apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-claim
spec:
  storageClassName: standard
  volumeName: "jenkins-home"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-config-claim
spec:
  storageClassName: standard
  volumeName: "jenkins-config"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-secrets-claim
spec:
  storageClassName: standard
  volumeName: "jenkins-secrets"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
