apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-home
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/jenkins-home/"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-config
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/jenkins-config/"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-secrets
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/jenkins-secrets/"
